# Generated by Django 4.1.5 on 2023-01-28 16:51

from django.db import migrations
import educata.models


class Migration(migrations.Migration):

    dependencies = [
        ('educata', '0003_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', educata.models.UserManager()),
            ],
        ),
    ]
