# Generated by Django 4.1.5 on 2023-01-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educata', '0006_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
